services:
  - type: web
    name: linguofy
    runtime: docker
    plan: free
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: GOOGLE_KEY
        sync: false
      - key: MONGO_URL
        sync: false
